version: '3.7'

services:
  db-dev:
    container_name: db-dev
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_vol_dev:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DEV_DB_NAME}
      MYSQL_USER: ${DEV_DB_USER}
      MYSQL_PASSWORD: ${DEV_DB_PASSWORD}
    ports:
      - 3306:3306
  api-dev:
    container_name: api-dev
    depends_on:
      - db-dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - '.:/app'
      - '/app/node_modules'
    command: bash -c 'sequelize db:migrate && sequelize-cli db:seed:all && npm run start:dev'
    env_file: ./.env
    ports:
      - 8080:8080
volumes:
  db_vol_dev:
